---
- hosts: aws_ec2
  user: ec2-user
  become: yes
  connection: ssh

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/london.pem"
    ansible_ssh_user: "ec2-user"
  tasks:
    - name: installing git
      action: yum name=git state=present
    - name: installing httpd
      command: yum install httpd -y
    - name: restarting httpd
      service: name=httpd state=restarted
    - name: getting code into server
      git:
        repo: "https://github.com/Sivaprasad-Software/my-app.git"
        dest: "/var/www/html/"
        version: "frontend"

